// Generated by https://quicktype.io

export interface FetchAllPokemonResponse {
    count:    number;
    next:     null;
    previous: null;
    results:  SmallPokemom[];
}

export interface SmallPokemom {
    name: string;
    url:  string;
}

export interface Pokemon{
    id: string;
    name: string;
    pic: string;
}